// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/airtable.ts";
import * as $2 from "./routes/styles.css.ts";
import * as $$0 from "./islands/Form.tsx";
import * as $$1 from "./islands/SliderJS.tsx";
import * as $$2 from "./islands/WhatsAppFloatButton.tsx";
import * as $$3 from "./islands/WhatsAppHeaderButton.tsx";
import * as $$4 from "./islands/WhatsAppModal.tsx";
import * as $$5 from "./islands/WhatsAppNormalButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/airtable.ts": $1,
    "./routes/styles.css.ts": $2,
  },
  islands: {
    "./islands/Form.tsx": $$0,
    "./islands/SliderJS.tsx": $$1,
    "./islands/WhatsAppFloatButton.tsx": $$2,
    "./islands/WhatsAppHeaderButton.tsx": $$3,
    "./islands/WhatsAppModal.tsx": $$4,
    "./islands/WhatsAppNormalButton.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
